### PR TITLE
Add a setting to remove the explanation on top of the units

### PR DESCRIPTION
**Pull request by sky2025**
feature update: setting to remove description on top of units.
OTIS username is sky2025

### CODE REVIEW

**Comment by Incompleteusern** [comment]
You'd wanna lint the djlint output and generate migrations.

**Comment by vEnhance** [comment]
This closes #264

**Comment by vEnhance** [comment]
Nice!

I'm going to change the variable name to something a little more accurate (`unit_description` is really misleading, I'd rather call it `show_portal_instructions` or something), but otherwise this looks good.

**Comment by vEnhance** [comment]
skyler can you give me permission to push things onto your branch, i'm getting perm denied

**Comment by vEnhance** [comment]
we all good

**Pull request merged**
