### PR TITLE
Update models.py

### PR DESCRIPTION
**Pull request by RadialFunc**
Adds the option to Lock a unit (removing it from unlocked, but stays in your curriculum). Feature #141 .

OTIS ID: 968

### CODE REVIEW

**Comment by Incompleteusern** [comment]
nice

**Comment by vEnhance** [comment]
@RadialFunc two notes:

(1) You need to generate a migration for model changes by running `python manage.py makemigrations` (which means for this pull request you won't be able to do it just from the web interface, sorry :P )
(2) Most of the petition processing is done in `aincrad/views.py` so you need to update the code there

**Comment by vEnhance** [comment]
EDIT to add: sorry, `aincrad/views.py` is fine, I forgot it already calls `run_accept`

**Comment by vEnhance** [comment]
wtf how did i lose the commit

**Comment by vEnhance** [comment]
seems I can't push to the remote branch now so I set up #155 instead

**Pull request closed without merging**
