### PR TITLE
Catalog Checklist completely.

### LINKED ISSUE #206: Catalog as a Checklist?
https://otis.evanchen.cc/core/catalog/ could color complete units into a different color.

Something like this
image

### PR DESCRIPTION
**Pull request by Incompleteusern**
Fixes #206 .
image

Ignore the horribly mangled git history as a result of my laziness.

### CODE REVIEW

**Comment by Incompleteusern** [comment]
Ok pyright wont shut up apparently

**Comment by Incompleteusern** [comment]
Oops ;-;

**Comment by Incompleteusern** [comment]
The construct
```python
                      {% if not forloop.last %}
                        {{ unit.code }},
                      {% else %}
                        {{ unit.code }}
                      {% endif %}
```
is rather stupid but djlint kind of forces it I think

**Comment by vEnhance** [comment]
i think we can just put check marks on the individual units rather than the group if we're going to have that information

also i'm happy to just drop the commas if it's that annoying

let me try that now

**Comment by vEnhance** [comment]
oh i see this is actually super annoying because it's a listview of unitgroup's rather than unit's

uhh

ok maybe i should rewrite it

**Comment by Incompleteusern** [comment]
Feel free to do so. It might end up being more roundabout though since the catalog is split into unit groups which are in turn split into units.

Also hopefully this has O(1) database queries, since appararently django filter on query set doesn't hit the database most of the time.

**Comment by vEnhance** [comment]
ok that should be a lot simpler now

**Comment by vEnhance** [comment]
does that look reasonable?

**Comment by Incompleteusern** [comment]
Yeah this is better. Not a fan of the emojis being in the subject group title (Coloring the text or something would be better IMO)

**Comment by Incompleteusern** [comment]
Yeah this is better. Not a fan of the emojis being in the subject group title (Coloring the text or something would be better IMO)

**Comment by Incompleteusern** [comment]
Codewise, everything is a lot better and cleaner lol. I'll make a poll in #billboards to ask what people prefer ig.

**Comment by vEnhance** [comment]
OK, thanks

**Pull request merged**
