### PR TITLE
Add market spades page and update links

### PR DESCRIPTION
**Pull request by coolbluealan**
Feature: Market spade page (#75 ) 

Student ID:  819

### CODE REVIEW

**Comment by vEnhance** [comment]
Thanks, this is nice. I made a couple small cosmetic/stylistic changes, but the overall PR looks great.

Here's the diff if you're curious what changed:
```diff
diff --git a/markets/templates/markets/market_list.html b/markets/templates/markets/market_list.html
index bd3b211..0654d57 100644
--- a/markets/templates/markets/market_list.html
+++ b/markets/templates/markets/market_list.html
@@ -39,7 +39,7 @@
     {% endfor %}
   </table>
   <p>
-    <a href="{% url "market-spades" %}">Spades earned from all markets</a>
+    <a href="{% url "market-spades" %}">Show your results from all previous markets</a>
   </p>
   {% if past %}
     <a href="{% url "market-list" %}">Show markets from this year</a>
diff --git a/markets/templates/markets/market_spades.html b/markets/templates/markets/market_spades.html
index dc17a45..b2f7061 100644
--- a/markets/templates/markets/market_spades.html
+++ b/markets/templates/markets/market_spades.html
@@ -1,9 +1,9 @@
 {% extends "layout.html" %}
 {% block title %}
-  Spades from Markets
+  Your historical market results
 {% endblock title %}
 {% block layout-content %}
-  {% if no_guesses %}
+  {% if not guesses %}
     <p>You have not completed any markets yet.</p>
   {% else %}
     <p>Below are all the markets you have participated in.</p>
@@ -25,11 +25,13 @@
         </tr>
       {% endfor %}
     </table>
-    <p>You have earned a total of {{ total|floatformat:2 }}♠ across {{ guesses.count }} markets.</p>
-    <p>Average spades per market: {{ avg|floatformat:2 }}</p>
+    <p>You have earned a total of <b>{{ total|floatformat:2 }}♠</b> across {{ guesses.count }} markets.</p>
+    <p>Average spades per market: {{ avg|floatformat:2 }}♠.</p>
   {% endif %}
   <p>
     <a href="{% url "market-list" %}">Show markets from this year</a>
   </p>
+  <p>
   <a href="{% url "market-list-past" %}">Show markets from past years</a>
+  </p>
 {% endblock layout-content %}
diff --git a/markets/views.py b/markets/views.py
index c953da3..522d36c 100644
--- a/markets/views.py
+++ b/markets/views.py
@@ -172,10 +172,8 @@ class MarketSpades(LoginRequiredMixin, ListView[Guess]):
     def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
         context = super().get_context_data(**kwargs)
         guesses = self.get_queryset()
-        if guesses is not None:
+        if guesses.exists():
             context.update(guesses.aggregate(total=Sum("score"), avg=Avg("score")))
-        else:
-            context["no_guesses"] = True
         return context
 
     def get_queryset(self) -> QuerySet[Guess]:
@@ -184,8 +182,8 @@ class MarketSpades(LoginRequiredMixin, ListView[Guess]):
                 user=self.request.user,
                 market__end_date__lt=timezone.now(),
             )
-            .order_by("-market__end_date")
             .select_related("market")
+            .order_by("-market__end_date")
         )
```

**Comment by vEnhance** [comment]
@coolbluealan Would you be able to write a unit test for this new view under `market/tests.py`? If you have questions on how this works, I can help.

Basically, you should create a new test under `MarketTests` and check that the page correctly shows the "no guesses" message for `alice` when logged in, then after `alice` submits a guess, gives the correct average and so on. The `freeze_time` method lets you freeze a specific time.

If you want to be very careful, you can also test that market results aren't leaked until the market ends, and maybe add a second or third market if you want to verify the average does what you think it does. 

After that, I will merge this.

**Comment by vEnhance** [comment]
BTW, I should mention that iirc, `if guesses is not None` will always return True, because `guesses` is a queryset object.

Much like how `[] is not None` is always True.

**Comment by coolbluealan** [comment]
> @coolbluealan Would you be able to write a unit test for this new view under `market/tests.py`? If you have questions on how this works, I can help.

I will try to do that.

**Comment by coolbluealan** [comment]
I'm not sure if this test is right. Also when running the market tests it gave many of this warning:
> The django.utils.timezone.utc alias is deprecated. Please update your code to use datetime.timezone.utc instead.

**Comment by vEnhance** [comment]
Thanks! I'll fix the utc issue on my end at some point (that's not your fault I think).

**Comment by vEnhance** [comment]
You should also have gotten the 9 spade bounty just now

**Pull request merged**
