### PR TITLE
Auto accept previous year units

### LINKED ISSUE #300: Auto-Unlock previous year units
> Units a person had in previous years could just be automatically unlocked in unit petition. That might be the cleanest way.

### PR DESCRIPTION
**Pull request by Incompleteusern**
Fixes #300 #318.

Automatically accepts petitions of a user that has students of another instance with that unit unlocked.

### CODE REVIEW

**Comment by vEnhance** [comment]
Some changes requested:

1. There's some random print statements that need to be fixed
2. I think this is an O(n) query where n is the number of times you've done OTIS, but it really should be O(1). Django should support something like `Student.objects.filter(user=student.user, curriculum__<something>=unit)`, I don't know off my head but I'd be shocked if it didn't exist.
3. Needs unit tests.

**Comment by vEnhance** [comment]
still waiting on unit tests here

**Comment by jatloe** [comment]
is this dead

**Comment by Incompleteusern** [comment]
I don't feel like working on this right now. I might finish unit tests when this OTIS semester is over.

**Comment by palindrome868wastaken** [comment]
what are unit tests?

**Comment by Incompleteusern** [comment]
Unit Tests should be done.

**Comment by chessisdabest** [comment]
Wonderful timing for the new year...

**Pull request merged**
