### PR TITLE
Unit Petition Logic Changes

### LINKED ISSUE #203: Option to drop locked units from curriculum
This shouldn't require Evan's permission, right?

### PR DESCRIPTION
**Pull request by Incompleteusern**
Fixes #203 

Also attempts to streamline inquiry logic through moving logic to a separate function while staying the same afaik, tests still pass,

It might be best to review this commit by commit.

### CODE REVIEW

**Comment by Incompleteusern** [comment]
Also this might require more extensive testing to see that logic isn't inadvertently broken

**Comment by Incompleteusern** [comment]
Why did it merge all the user market code ;-;

**Comment by vEnhance** [comment]
Can you write some tests in `roster/tests.py` to make sure this logic checks out?

**Comment by Incompleteusern** [comment]
`test_inquiry` tests are already decently robust, it detected the two times I messed up the staff check and another time.

**Comment by Incompleteusern** [comment]
Will write tests for this logic though

**Pull request merged**
