### PR TITLE
Diamond in Wiki Based off pk

### PR DESCRIPTION
**Pull request by Incompleteusern**
A few reasons for this:
- You can't make a wiki page currently with a diamond without leaking it
- The wiki diamond isn't special since there's also a wikipage for Start Here as a result
- More diamond pages would be cool

image
image

The tag is only expanded to show information if the diamond is not user made and at least one person has found the diamond.

### CODE REVIEW

**Comment by Incompleteusern** [comment]
Also fixes #207 ig, though if this pr is denied that should also be closed.

**Comment by Incompleteusern** [comment]
It's fine to close this pr if deemed unnecessary/too complex btw.

**Comment by vEnhance** [comment]
We can give this a try.

**Comment by vEnhance** [comment]
I guess this lets you get the name and description of a diamond even if you don't have it unlocked, but the wiki is advertised to contain spoilers anyways.

**Pull request merged**
