### PR TITLE
Update CONTRIBUTING.mkd

### PR DESCRIPTION
**Pull request by arch2019**
Flex a little bit.

### CODE REVIEW

**Comment by vEnhance** [comment]
do you actually want me to merge this or are you just testing stuff out

**Comment by arch2019** [comment]
Just testing stuff out. I am relatively new to github so I was just seeing
how stuff works.

**Comment by vEnhance** [comment]
sounds good :P

**Comment by arch2019** [comment]
Aghhh there is a diamond here right?

**Comment by vEnhance** [comment]
No, not in this document.

**Pull request closed without merging**
